#!/bin/bash

xhost +

# Option 1 : Run docker as root
# --privileged : for importing tty device and fixing libGL,ALSA error while executing gazebo
# Remove : export containerId=$(docker ps -l -q)
#          --env="QT_X11_NO_MITSHM=1" \
 
docker run -it \
	   --privileged \
           --net=host \
	   --runtime nvidia \
	   -e DISPLAY=$DISPLAY \
	   -v /tmp/.X11-unix/:/tmp/.X11-unix \
	   alonzo3569/arm64-nvidia:moos

xhost -
