#!/bin/bash

xhost +local:root

# Option 1 : Run docker as root
# --privileged : for importing tty device and fixing libGL,ALSA error while executing gazebo
# Remove : export containerId=$(docker ps -l -q)
#          --env="QT_X11_NO_MITSHM=1" \
 
docker run -it \
    --rm \
    --privileged \
    --env="DISPLAY" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    alonzo3569/desktop:melodic

# Option 2 : Run docker as local usr, need sudo while running gazebo
#docker run -it \
#    --rm \
#    --privileged \
#    --user=$(id -u $USER):$(id -g $USER) \
#    --env="DISPLAY" \
#    --workdir="/home/$USER" \
#    --volume="/home/$USER:/home/$USER" \
#    --volume="/etc/group:/etc/group:ro" \
#    --volume="/etc/passwd:/etc/passwd:ro" \
#    --volume="/etc/shadow:/etc/shadow:ro" \
#    --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
#    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
#    alonzo3569/bionic:melodic
